#!/usr/bin/env npx tsx
/*
 * install-stop-hook.ts — manage Codex Stop hook manifest without shell.
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const scriptDir = path.dirname(path.resolve(process.argv[1] || __filename));
const boardRoot = path.resolve(process.env.AUTOFLOW_BOARD_ROOT || process.env.BOARD_ROOT || path.join(scriptDir, ".."));
const projectRoot = path.resolve(process.env.PROJECT_ROOT || process.env.AUTOFLOW_PROJECT_ROOT || path.join(boardRoot, ".."));

const action = process.argv[2] || "install";
if (!["install", "remove", "status"].includes(action) || process.argv.length > 3) {
  process.stderr.write("Usage: install-stop-hook.ts [install|remove|status]\n");
  process.exit(1);
}

const manifestPath = resolveManifestPath(process.env.AUTOFLOW_CODEX_HOOKS_PATH || process.env.CODEX_HOOKS_PATH || path.join(os.homedir(), ".codex", "hooks.json"));
const commandText = process.env.AUTOFLOW_STOP_HOOK_COMMAND || quoteCommand(path.join(__dirname, "check-stop.ts"));
const timeoutValue = positiveInt(process.env.AUTOFLOW_STOP_HOOK_TIMEOUT || "", 30);

const manifestExists = fs.existsSync(manifestPath);
let data: any = {};
if (manifestExists) {
  const raw = fs.readFileSync(manifestPath, "utf8").trim();
  data = raw ? JSON.parse(raw) : {};
}
if (!data || typeof data !== "object" || Array.isArray(data)) {
  throw new Error(`hook manifest root must be a JSON object: ${manifestPath}`);
}

let hooks = data.hooks;
if (hooks === undefined) hooks = {};
if (!hooks || typeof hooks !== "object" || Array.isArray(hooks)) {
  throw new Error(`hook manifest 'hooks' must be a JSON object: ${manifestPath}`);
}
data.hooks = hooks;

let stopEntries = hooks.Stop;
if (stopEntries === undefined) stopEntries = [];
if (!Array.isArray(stopEntries)) throw new Error(`hook manifest 'hooks.Stop' must be a JSON array: ${manifestPath}`);
hooks.Stop = stopEntries;

const hookMatches = (hook: any): boolean => hook && typeof hook === "object" && !Array.isArray(hook) && hook.type === "command" && hook.command === commandText;
const entryMatches = (entry: any): boolean => entry && typeof entry === "object" && !Array.isArray(entry) && Array.isArray(entry.hooks) && entry.hooks.some(hookMatches);

const installedBefore = stopEntries.some(entryMatches);
let changed = false;
if (action === "install" && !installedBefore) {
  stopEntries.push({ hooks: [{ type: "command", command: commandText, timeout: timeoutValue }] });
  changed = true;
}
if (action === "remove") {
  hooks.Stop = stopEntries.flatMap((entry: any) => {
    if (!entry || typeof entry !== "object" || Array.isArray(entry) || !Array.isArray(entry.hooks)) return [entry];
    const filtered = entry.hooks.filter((hook: any) => !hookMatches(hook));
    if (filtered.length !== entry.hooks.length) changed = true;
    return filtered.length > 0 ? [{ ...entry, hooks: filtered }] : [];
  });
}

const installedAfter = (hooks.Stop || []).some(entryMatches);
if ((action === "install" || action === "remove") && changed) {
  if (!hooks.Stop || hooks.Stop.length === 0) delete hooks.Stop;
  if (!manifestExists) {
    data.name ??= "autoflow";
    data.description ??= "Generated by Autoflow stop-hook installer.";
  }
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  const tempPath = path.join(path.dirname(manifestPath), `.autoflow-hooks-${process.pid}-${Date.now()}.json`);
  fs.writeFileSync(tempPath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
  fs.renameSync(tempPath, manifestPath);
}

printPairs({
  manifest_path: manifestPath,
  manifest_exists_before: manifestExists ? "true" : "false",
  manifest_changed: changed ? "true" : "false",
  installed_before: installedBefore ? "true" : "false",
  installed_after: installedAfter ? "true" : "false",
  status: installedAfter ? "installed" : "missing",
  action,
  board_root: boardRoot,
  project_root: projectRoot,
  command: commandText,
});

function resolveManifestPath(rawPath: string): string {
  const raw = rawPath.replace(/^['"]+|['"]+$/g, "");
  if (raw === "~") return os.homedir();
  if (raw.startsWith("~/")) return path.join(os.homedir(), raw.slice(2));
  if (path.isAbsolute(raw)) return path.normalize(raw);
  return path.resolve(process.cwd(), raw);
}

function quoteCommand(commandPath: string): string {
  return `"${commandPath.replace(/"/g, '\\"')}"`;
}

function positiveInt(raw: string, fallback: number): number {
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function printPairs(fields: Record<string, string>): void {
  for (const [key, value] of Object.entries(fields)) process.stdout.write(`${key}=${value}\n`);
}
