#!/usr/bin/env bash

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

ensure_expected_role "plan"

requested_id="${1:-}"
if [ -n "$requested_id" ]; then
  plan_id="$(normalize_id "$requested_id")"
  target_plan="$(plan_path "$plan_id")"
else
  target_plan="$(lowest_ready_plan || true)"
  if [ -z "$target_plan" ]; then
    fail_or_idle "No ready plan file found." "no_ready_plan"
  fi
  plan_id="$(extract_numeric_id "$target_plan")"
fi

if [ ! -f "$target_plan" ]; then
  echo "Plan file not found: $target_plan" >&2
  exit 1
fi

project_spec_raw="$(extract_reference_value "$target_plan" "Spec References" "Project Spec")"
project_spec_ref="$(strip_markdown_code_ticks "$project_spec_raw")"
feature_spec_raw="$(extract_reference_value "$target_plan" "Spec References" "Feature Spec")"
feature_spec_ref="$(strip_markdown_code_ticks "$feature_spec_raw")"

if [ -z "$project_spec_ref" ]; then
  echo "Project spec reference is required in $target_plan" >&2
  exit 1
fi

if ! board_file_exists "$project_spec_ref"; then
  echo "Referenced project spec does not exist: ${BOARD_ROOT}/${project_spec_ref}" >&2
  exit 1
fi

allowed_paths="$(extract_allowed_paths_block "$target_plan")"
if [ -z "$allowed_paths" ]; then
  echo "Allowed Paths must be declared in $target_plan" >&2
  exit 1
fi

candidates_file="$(mktemp)"
extract_execution_candidates "$target_plan" > "$candidates_file"
if [ ! -s "$candidates_file" ]; then
  rm -f "$candidates_file"
  fail_or_idle "No unchecked execution candidates in $target_plan" "no_execution_candidates"
fi

generated_count=0
while IFS= read -r candidate; do
  [ -n "$candidate" ] || continue

  if ticket_exists_for_plan_candidate "$plan_id" "$candidate"; then
    continue
  fi

  ticket_id="$(next_ticket_id)"
  ticket_file="$(ticket_path "todo" "$ticket_id")"
  timestamp="$(now_iso)"

  cat > "$ticket_file" <<EOF
# Ticket

## Ticket

- ID: ${ticket_id}
- Title: ${candidate}
- Stage: todo
- Owner: unassigned
- Claimed By: unclaimed
- Execution Owner: unassigned
- Verifier Owner: unassigned
- Last Updated: ${timestamp}

## Goal

- 이번 작업의 목표: ${candidate}

## References

- Project Spec: \`${project_spec_ref}\`
- Feature Spec: ${feature_spec_ref:+\`${feature_spec_ref}\`}
- Plan Source: \`rules/plan/plan_${plan_id}.md\`

## Allowed Paths

${allowed_paths}

## Done When

- [ ] ${candidate} 작업 결과가 반영되었다.
- [ ] 관련 메모와 결과가 티켓에 기록되었다.

## Next Action

- 다음에 바로 이어서 할 일: todo worker 가 이 티켓을 claim 하고 execution owner 를 배정

## Resume Context

- 현재 상태 요약: plan 에서 생성된 새 todo 티켓
- 직전 작업: scripts/start-plan.sh 로 생성됨
- 재개 시 먼저 볼 것: Goal, Allowed Paths, Done When, Execution Owner

## Notes

- Generated by scripts/start-plan.sh at ${timestamp}

## Verification

- Run file:
- Result:

## Result

- Summary:
- Remaining risk:

## Path Notes

- \`References\` 는 \`BOARD_ROOT\` 상대 경로다.
- \`Allowed Paths\` 는 \`PROJECT_ROOT\` 상대 경로다.
EOF

  append_generated_ticket "$target_plan" "tickets_${ticket_id}.md generated from candidate: ${candidate}"
  generated_count=$((generated_count + 1))
  printf 'generated=%s\n' "$ticket_file"
done < "$candidates_file"

rm -f "$candidates_file"

if [ "$generated_count" -gt 0 ]; then
  replace_scalar_field_in_section "$target_plan" "## Plan" "Status" "ticketed"
fi

printf 'plan=%s\n' "$target_plan"
printf 'board_root=%s\n' "$BOARD_ROOT"
printf 'project_root=%s\n' "$PROJECT_ROOT"
