import * as shared from "../../../shared/runner-tool";

type JsonObject = shared.JsonObject;
type QueueItem = shared.QueueItem;
type WorkerTicketItem = shared.WorkerTicketItem;

const {
  crypto,
  fs,
  path,
  spawnSync,
  utils,
  SCRIPT_DIR,
  DEFAULT_BOARD_ROOT,
  DEFAULT_PROJECT_ROOT,
  BOARD_ROOT,
  PROJECT_ROOT,
  TICKETS_ROOT,
  args,
  isReadyWorktree,
  listQueueItems,
  readQueueItem,
  readAnyPriority,
  readTitle,
  readStatus,
  listWorkerTicketItems,
  readWorkerTicketItem,
  workerTicketSort,
  ticketItemOwnedByRunner,
  runnerTokenMatches,
  canonicalRunnerId,
  claimToken,
  pathConflictGuardEnabled,
  collectTicketConflicts,
  pathsOverlap,
  normalizeRelPath,
  requireTicket,
  resolveTicketPath,
  acquireDispatchLock,
  releaseDispatchLock,
  readWorktreeStatus,
  ensureWorkerTicketWorktree,
  worktreeModeDisabled,
  defaultTicketWorktreePath,
  isGitWorktree,
  gitBranchExists,
  hydrateWorktreeDependencies,
  findDependencyDirs,
  excludeWorktreePath,
  doneWhenCheck,
  diffCheck,
  diffStats,
  readVerifierEvidence,
  recordVerifierDecision,
  findTicketById,
  workerRunnerIdFromTicket,
  markWorkerTicketVerified,
  writeVerifierLog,
  verifierOkMarkerPath,
  diffPatch,
  capTextByBytes,
  cleanSectionLines,
  fileMtimeIso,
  compactIso,
  isoLatencySeconds,
  statusPorcelainPaths,
  gitLines,
  numstatLineCount,
  numstatByFile,
  updateWorkerState,
  replaceSectionBlock,
  bulletize,
  readOptionalTextFile,
  stripTicks,
  oneLine,
  unique,
  git,
  spawnTsScript,
  spawnOutputText,
  wikiSourceGroups,
  hashFiles,
  boardDirName,
  autoflowCliPath,
  emitAutoflowResult,
  parseKeyValueOutput,
  resolveLocalFile,
  resolveWikiWritablePath,
  parseNumstat,
  readWikiStatusItem,
  safeLineCount,
  wikiCategory,
  wikiFileWeight,
  readWritePayload,
  validatePrdContent,
  validateTicketContent,
  requireSection,
  collectUsedIds,
  pruneReservations,
  releaseReservation,
  collectFiles,
  resolveBoardPath,
  validateNoUnsafeWrite,
  writeAtomic,
  extractIdFromContent,
  extractBulletSectionFromText,
  extractChecklistFromText,
  extractSectionLines,
  normalizePriority,
  priorityRank,
  idFromPath,
  normalizeId,
  getArg,
  getArgs,
  hasFlag,
  positiveInt,
  numberValue,
  safeSegment,
  currentRunnerId,
  readRoleAssignment,
  compactAssignment,
  boardRel,
  stringValue,
  safeIsFile,
  ensureTrailingNewline,
  escapeRe,
  ok,
  fail
} = shared;

export function cmdWikiSourceSnapshot(): void {
  const runnerId = currentRunnerId("wiki");
  const assignmentCheck = readRoleAssignment("wiki", runnerId);
  const assignmentIsScoped = Boolean(assignmentCheck.assignment);
  const maxItems = positiveInt(getArg("--max-items") || "", 20);
  const groups = wikiSourceGroups();
  const allFiles = Object.values(groups).flat();
  const recent = assignmentCheck.ok ? allFiles
    .map((file) => {
      const stat = fs.statSync(file);
      return {
        path: boardRel(file),
        size: stat.size,
        mtime: new Date(stat.mtimeMs).toISOString().replace(/\.\d+Z$/, "Z"),
      };
    })
    .sort((a, b) => b.mtime.localeCompare(a.mtime) || a.path.localeCompare(b.path))
    .slice(0, maxItems) : [];

  ok({
    tool: "wiki.source-snapshot",
    runner: runnerId,
    assignment_required: assignmentIsScoped,
    assignment_status: assignmentCheck.ok ? (assignmentIsScoped ? "active" : "fixed_runner") : assignmentCheck.reason,
    assignment: compactAssignment(assignmentCheck.assignment),
    generated_at: utils.nowIso(),
    board_root: BOARD_ROOT,
    project_root: PROJECT_ROOT,
    source_counts: Object.fromEntries(Object.entries(groups).map(([name, files]) => [name, files.length])),
    total_source_files: allFiles.length,
    content_fingerprint: hashFiles(allFiles),
    recent,
  });
}
