#!/usr/bin/env bash

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

usage() {
  echo "Usage: install-stop-hook.sh [install|remove|status]" >&2
}

resolve_manifest_path() {
  local raw="${1:-$HOME/.codex/hooks.json}"

  case "$raw" in
    "~")
      printf '%s' "$HOME"
      ;;
    "~/"*)
      printf '%s/%s' "$HOME" "${raw#~/}"
      ;;
    /*)
      printf '%s' "$raw"
      ;;
    [A-Za-z]:[\\/]*)
      normalize_runtime_path "$raw"
      ;;
    *)
      printf '%s/%s' "$(pwd)" "$raw"
      ;;
  esac
}

detect_json_runtime() {
  if command -v python3 >/dev/null 2>&1; then
    printf 'python3'
    return 0
  fi

  if command -v python >/dev/null 2>&1; then
    printf 'python'
    return 0
  fi

  if command -v node >/dev/null 2>&1; then
    printf 'node'
    return 0
  fi

  return 1
}

default_stop_hook_command() {
  shell_quote "${BOARD_ROOT}/scripts/check-stop.sh"
}

run_with_python() {
  local runtime_bin="$1"
  local manifest_path="$2"
  local action="$3"
  local command_text="$4"
  local timeout="$5"

  "$runtime_bin" - "$manifest_path" "$action" "$command_text" "$timeout" <<'PY'
import json
import os
import sys
import tempfile

manifest_path, action, command_text, timeout_raw = sys.argv[1:5]
timeout_value = int(timeout_raw)

manifest_exists = os.path.exists(manifest_path)
if manifest_exists:
    with open(manifest_path, "r", encoding="utf-8") as fh:
        raw = fh.read().strip()
    data = json.loads(raw) if raw else {}
else:
    data = {}

if not isinstance(data, dict):
    raise SystemExit(f"hook manifest root must be a JSON object: {manifest_path}")

hooks = data.get("hooks")
if hooks is None:
    hooks = {}
elif not isinstance(hooks, dict):
    raise SystemExit(f"hook manifest 'hooks' must be a JSON object: {manifest_path}")
data["hooks"] = hooks

stop_entries = hooks.get("Stop")
if stop_entries is None:
    stop_entries = []
elif not isinstance(stop_entries, list):
    raise SystemExit(f"hook manifest 'hooks.Stop' must be a JSON array: {manifest_path}")
hooks["Stop"] = stop_entries

def hook_matches(hook):
    return isinstance(hook, dict) and hook.get("type") == "command" and hook.get("command") == command_text

def entry_matches(entry):
    return isinstance(entry, dict) and isinstance(entry.get("hooks"), list) and any(hook_matches(h) for h in entry["hooks"])

installed_before = any(entry_matches(entry) for entry in stop_entries)
changed = False

if action == "install":
    if not installed_before:
        stop_entries.append({
            "hooks": [
                {
                    "type": "command",
                    "command": command_text,
                    "timeout": timeout_value,
                }
            ]
        })
        changed = True
elif action == "remove":
    new_stop_entries = []
    for entry in stop_entries:
        if not isinstance(entry, dict):
            new_stop_entries.append(entry)
            continue

        hooks_list = entry.get("hooks")
        if not isinstance(hooks_list, list):
            new_stop_entries.append(entry)
            continue

        filtered_hooks = [hook for hook in hooks_list if not hook_matches(hook)]
        if len(filtered_hooks) != len(hooks_list):
            changed = True

        if filtered_hooks:
            new_entry = dict(entry)
            new_entry["hooks"] = filtered_hooks
            new_stop_entries.append(new_entry)

    hooks["Stop"] = new_stop_entries

installed_after = any(entry_matches(entry) for entry in hooks.get("Stop", []))

if action in ("install", "remove") and changed:
    if not hooks.get("Stop"):
        hooks.pop("Stop", None)

    if not manifest_exists:
        data.setdefault("name", "autoflow")
        data.setdefault("description", "Generated by Autoflow stop-hook installer.")

    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    fd, temp_path = tempfile.mkstemp(prefix="autoflow-hooks-", suffix=".json", dir=os.path.dirname(manifest_path) or None)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        os.replace(temp_path, manifest_path)
    finally:
        if os.path.exists(temp_path):
            os.unlink(temp_path)

print(f"manifest_path={manifest_path}")
print(f"manifest_exists_before={'true' if manifest_exists else 'false'}")
print(f"manifest_changed={'true' if changed else 'false'}")
print(f"installed_before={'true' if installed_before else 'false'}")
print(f"installed_after={'true' if installed_after else 'false'}")
print(f"status={'installed' if installed_after else 'missing'}")
PY
}

run_with_node() {
  local manifest_path="$1"
  local action="$2"
  local command_text="$3"
  local timeout="$4"

  node - "$manifest_path" "$action" "$command_text" "$timeout" <<'NODE'
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const [manifestPath, action, commandText, timeoutRaw] = process.argv.slice(2);
const timeoutValue = Number.parseInt(timeoutRaw, 10);

const manifestExists = fs.existsSync(manifestPath);
let data = {};

if (manifestExists) {
  const raw = fs.readFileSync(manifestPath, "utf8").trim();
  data = raw ? JSON.parse(raw) : {};
}

if (!data || typeof data !== "object" || Array.isArray(data)) {
  throw new Error(`hook manifest root must be a JSON object: ${manifestPath}`);
}

let hooks = data.hooks;
if (hooks === undefined) {
  hooks = {};
} else if (!hooks || typeof hooks !== "object" || Array.isArray(hooks)) {
  throw new Error(`hook manifest 'hooks' must be a JSON object: ${manifestPath}`);
}
data.hooks = hooks;

let stopEntries = hooks.Stop;
if (stopEntries === undefined) {
  stopEntries = [];
} else if (!Array.isArray(stopEntries)) {
  throw new Error(`hook manifest 'hooks.Stop' must be a JSON array: ${manifestPath}`);
}
hooks.Stop = stopEntries;

function hookMatches(hook) {
  return hook && typeof hook === "object" && !Array.isArray(hook) &&
    hook.type === "command" &&
    hook.command === commandText;
}

function entryMatches(entry) {
  return entry && typeof entry === "object" && !Array.isArray(entry) &&
    Array.isArray(entry.hooks) &&
    entry.hooks.some((hook) => hookMatches(hook));
}

const installedBefore = stopEntries.some((entry) => entryMatches(entry));
let changed = false;

if (action === "install") {
  if (!installedBefore) {
    stopEntries.push({
      hooks: [
        {
          type: "command",
          command: commandText,
          timeout: timeoutValue
        }
      ]
    });
    changed = true;
  }
} else if (action === "remove") {
  const newStopEntries = [];
  for (const entry of stopEntries) {
    if (!entry || typeof entry !== "object" || Array.isArray(entry) || !Array.isArray(entry.hooks)) {
      newStopEntries.push(entry);
      continue;
    }

    const filteredHooks = entry.hooks.filter((hook) => !hookMatches(hook));
    if (filteredHooks.length !== entry.hooks.length) {
      changed = true;
    }

    if (filteredHooks.length) {
      newStopEntries.push({
        ...entry,
        hooks: filteredHooks
      });
    }
  }

  hooks.Stop = newStopEntries;
}

const installedAfter = (hooks.Stop || []).some((entry) => entryMatches(entry));

if ((action === "install" || action === "remove") && changed) {
  if (!hooks.Stop || !hooks.Stop.length) {
    delete hooks.Stop;
  }

  if (!manifestExists) {
    if (!("name" in data)) data.name = "autoflow";
    if (!("description" in data)) data.description = "Generated by Autoflow stop-hook installer.";
  }

  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  const tempPath = path.join(path.dirname(manifestPath), `.autoflow-hooks-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}.json`);
  fs.writeFileSync(tempPath, `${JSON.stringify(data, null, 2)}${os.EOL}`, "utf8");
  fs.renameSync(tempPath, manifestPath);
}

console.log(`manifest_path=${manifestPath}`);
console.log(`manifest_exists_before=${manifestExists ? "true" : "false"}`);
console.log(`manifest_changed=${changed ? "true" : "false"}`);
console.log(`installed_before=${installedBefore ? "true" : "false"}`);
console.log(`installed_after=${installedAfter ? "true" : "false"}`);
console.log(`status=${installedAfter ? "installed" : "missing"}`);
NODE
}

action="${1:-install}"
case "$action" in
  install|remove|status)
    ;;
  *)
    usage
    exit 1
    ;;
esac

if [ $# -gt 1 ]; then
  usage
  exit 1
fi

manifest_path="$(resolve_manifest_path "${AUTOFLOW_CODEX_HOOKS_PATH:-${CODEX_HOOKS_PATH:-$HOME/.codex/hooks.json}}")"
command_text="${AUTOFLOW_STOP_HOOK_COMMAND:-$(default_stop_hook_command)}"
timeout_value="${AUTOFLOW_STOP_HOOK_TIMEOUT:-30}"
json_runtime="$(detect_json_runtime || true)"

if [ -z "$json_runtime" ]; then
  echo "install-stop-hook.sh requires python3, python, or node to update Codex hook JSON." >&2
  exit 1
fi

case "$json_runtime" in
  python3|python)
    run_with_python "$json_runtime" "$manifest_path" "$action" "$command_text" "$timeout_value"
    ;;
  node)
    run_with_node "$manifest_path" "$action" "$command_text" "$timeout_value"
    ;;
  *)
    echo "Unsupported JSON runtime: ${json_runtime}" >&2
    exit 1
    ;;
esac

printf 'action=%s\n' "$action"
printf 'board_root=%s\n' "$BOARD_ROOT"
printf 'project_root=%s\n' "$PROJECT_ROOT"
printf 'command=%s\n' "$command_text"
