import {path, out, type ProjectContext} from "../context";
import {readRunnerState, runnerEffectiveStateStatus} from "./state";
import {runnerConfigFingerprint, runnerStringFieldDefaults} from "./serialize";

export function outputRunner(index: number, ctx: ProjectContext, runner: Record<string, string>): void {
    const prefix = `runner.${index}.`;
    const state = readRunnerState(ctx, runner.id || "");
    const stateStatus = runnerEffectiveStateStatus(state);
    const configFingerprint = runnerConfigFingerprint(runner);
    const field = (key: string, fallback = "") => runner[key] ?? fallback;

    out(`${prefix}id=${field("id")}`);
    out(`${prefix}role=${field("role")}`);
    out(`${prefix}agent=${field("agent", runnerStringFieldDefaults.agent)}`);
    out(`${prefix}codex_history=${field("codex_history", runnerStringFieldDefaults.codex_history)}`);
    out(`${prefix}model=${field("model", runnerStringFieldDefaults.model)}`);
    out(`${prefix}reasoning=${field("reasoning", runnerStringFieldDefaults.reasoning)}`);
    out(`${prefix}mode=${field("mode", runnerStringFieldDefaults.mode)}`);
    out(`${prefix}interval_seconds=${field("interval_seconds", runnerStringFieldDefaults.interval_seconds)}`);
    out(`${prefix}interval_effective_seconds=${field("interval_seconds", runnerStringFieldDefaults.interval_seconds)}`);
    out(`${prefix}enabled=${field("enabled", runnerStringFieldDefaults.enabled)}`);
    out(`${prefix}realtime_enabled=${field("realtime_enabled", runnerStringFieldDefaults.realtime_enabled)}`);
    out(`${prefix}command=${field("command", "")}`);
    out(`${prefix}command_preview=${field("command", "")}`);
    out(`${prefix}config_fingerprint=${configFingerprint}`);
    out(`${prefix}applied_config_fingerprint=${state.applied_config_fingerprint || state.config_fingerprint || configFingerprint}`);
    out(`${prefix}config_applied_at=${state.config_applied_at || state.updated_at || state.last_event_at || ""}`);
    out(`${prefix}state_status=${stateStatus}`);
    out(`${prefix}pid=${stateStatus === "running" ? state.pid || "" : ""}`);
    out(`${prefix}started_at=${state.started_at || ""}`);
    out(`${prefix}last_event_at=${state.last_event_at || state.updated_at || ""}`);
    out(`${prefix}last_adapter_chunk_at=${state.last_adapter_chunk_at || ""}`);
    out(`${prefix}active_item=${state.active_item || ""}`);
    out(`${prefix}active_ticket_id=${state.active_ticket_id || ""}`);
    out(`${prefix}active_ticket_title=${state.active_ticket_title || ""}`);
    out(`${prefix}active_stage=${state.active_stage || ""}`);
    out(`${prefix}active_spec_ref=${state.active_spec_ref || ""}`);
    out(`${prefix}active_recovery_reason=${state.active_recovery_reason || ""}`);
    out(`${prefix}active_recovery_status=${state.active_recovery_status || ""}`);
    out(`${prefix}active_recovery_failure_class=${state.active_recovery_failure_class || ""}`);
    out(`${prefix}last_result=${state.last_result || ""}`);
    out(`${prefix}last_runtime_log=${state.last_runtime_log || ""}`);
    out(`${prefix}last_prompt_log=${state.last_prompt_log || ""}`);
    out(`${prefix}last_stdout_log=${state.last_stdout_log || ""}`);
    out(`${prefix}last_stderr_log=${state.last_stderr_log || ""}`);
    out(`${prefix}artifact_status=${state.artifact_status || ""}`);
    out(`${prefix}artifact_runtime_status=${state.artifact_runtime_status || ""}`);
    out(`${prefix}artifact_prompt_status=${state.artifact_prompt_status || ""}`);
    out(`${prefix}artifact_stdout_status=${state.artifact_stdout_status || ""}`);
    out(`${prefix}artifact_stderr_status=${state.artifact_stderr_status || ""}`);
    out(`${prefix}last_log_line=${state.last_log_line || ""}`);
    out(`${prefix}cumulative_tokens=${state.cumulative_tokens || "0"}`);
    out(`${prefix}last_turn_tokens=${state.last_turn_tokens || "0"}`);
    out(`${prefix}last_turn_input_tokens=${state.last_turn_input_tokens || "0"}`);
    out(`${prefix}last_turn_output_tokens=${state.last_turn_output_tokens || "0"}`);
    out(`${prefix}last_turn_cache_read_tokens=${state.last_turn_cache_read_tokens || "0"}`);
    out(`${prefix}last_turn_cache_create_tokens=${state.last_turn_cache_create_tokens || "0"}`);
    out(`${prefix}last_turn_at=${state.last_turn_at || ""}`);
    out(`${prefix}last_turn_tick_id=${state.last_turn_tick_id || ""}`);
    out(`${prefix}token_source=${state.token_source || "none"}`);
    out(`${prefix}last_token_usage_source=${state.last_token_usage_source || state.token_source || "none"}`);
    out(`${prefix}cumulative_code_files_changed=${state.cumulative_code_files_changed || "0"}`);
    out(`${prefix}cumulative_code_insertions=${state.cumulative_code_insertions || "0"}`);
    out(`${prefix}cumulative_code_deletions=${state.cumulative_code_deletions || "0"}`);
    out(`${prefix}cumulative_code_volume=${state.cumulative_code_volume || "0"}`);
    out(`${prefix}cumulative_code_net_delta=${state.cumulative_code_net_delta || "0"}`);
    out(`${prefix}last_code_ticket_id=${state.last_code_ticket_id || ""}`);
    out(`${prefix}last_code_files_changed=${state.last_code_files_changed || "0"}`);
    out(`${prefix}last_code_insertions=${state.last_code_insertions || "0"}`);
    out(`${prefix}last_code_deletions=${state.last_code_deletions || "0"}`);
    out(`${prefix}last_code_volume=${state.last_code_volume || "0"}`);
    out(`${prefix}last_code_net_delta=${state.last_code_net_delta || "0"}`);
    out(`${prefix}last_code_reported_at=${state.last_code_reported_at || ""}`);
    out(`${prefix}code_source=${state.code_source || "none"}`);
    out(`${prefix}state_path=${path.join(ctx.boardRoot, "runners", "state", `${runner.id}.state`)}`);
    out(`${prefix}log_path=${path.join(ctx.boardRoot, "runners", "logs")}`);
}
