import {crypto, fs, type ProjectContext} from "../context";
import {fail} from "../context";
import {runnerConfigWritePath} from "./paths";

export const runnerConfigFieldOrder = [
    "id",
    "role",
    "agent",
    "codex_history",
    "model",
    "reasoning",
    "mode",
    "interval_seconds",
    "enabled",
    "command",
];

export const runnerStringFieldDefaults: Record<string, string> = {
    agent: "codex",
    codex_history: "isolated",
    model: "",
    reasoning: "medium",
    mode: "loop",
    interval_seconds: "60",
    enabled: "true",
    command: "",
};

function isScheduledLoopField(key: string): boolean {
    return key === "mode" || key === "interval_seconds";
}

export function normalizeRunnerReasoningValue(agent: string, value: string): string {
    const normalizedAgent = String(agent || "").toLowerCase();
    const normalized = String(value || "").trim().toLowerCase();
    const options: Record<string, string[]> = {
        codex: ["medium", "high", "xhigh"],
        claude: ["medium", "high", "xhigh", "max"],
    };
    const allowed = options[normalizedAgent];
    if (!allowed) return normalized;
    return allowed.includes(normalized) ? normalized : "medium";
}

export function runnerConfigFingerprint(runner: Record<string, string>): string {
    const body = runnerConfigFieldOrder
        .filter((key) => !isScheduledLoopField(key))
        .map((key) => {
            const value = key === "reasoning"
                ? normalizeRunnerReasoningValue(runner.agent || "codex", runner[key] ?? "")
                : runner[key] ?? "";
            return `${key}=${value}`;
        })
        .join("\n");
    return crypto.createHash("sha256").update(body).digest("hex").slice(0, 16);
}

export function formatTomlValue(key: string, value: string): string {
    if (key === "enabled" && /^(true|false)$/i.test(value)) {
        return value.toLowerCase();
    }
    if (key === "interval_seconds" && /^\d+$/.test(value)) {
        return value;
    }
    return JSON.stringify(value);
}

export function serializeRunnerConfig(runners: Array<Record<string, string>>): string {
    const lines = [
        "# Autoflow runner configuration (local override).",
        "# Generated by `autoflow runners set/add/remove`; project-local and gitignored by default.",
        "",
    ];
    for (const runner of runners) {
        const runnerId = runner.id || "";
        lines.push(`[runners.${JSON.stringify(runnerId)}]`);
        const known = new Set(runnerConfigFieldOrder);
        for (const key of runnerConfigFieldOrder) {
            if (isScheduledLoopField(key)) {
                continue;
            }
            if (runner[key] === undefined && runnerStringFieldDefaults[key] === undefined) {
                continue;
            }
            const rawValue = runner[key] ?? runnerStringFieldDefaults[key] ?? "";
            const value = key === "reasoning" ? normalizeRunnerReasoningValue(runner.agent || "codex", rawValue) : rawValue;
            lines.push(`${key} = ${formatTomlValue(key, value)}`);
        }
        const extraKeys = Object.keys(runner)
            .filter((key) => !known.has(key))
            .sort();
        for (const key of extraKeys) {
            lines.push(`${key} = ${formatTomlValue(key, runner[key] || "")}`);
        }
        lines.push("");
    }
    return `${lines.join("\n").trimEnd()}\n`;
}

export function writeRunnerConfig(ctx: ProjectContext, runners: Array<Record<string, string>>): string {
    const target = runnerConfigWritePath(ctx);
    fs.writeFileSync(target, serializeRunnerConfig(runners));
    return target;
}

export function runnerUpdateEntries(values: string[]): Record<string, string> {
    const updates: Record<string, string> = {};
    for (const value of values) {
        const index = value.indexOf("=");
        if (index <= 0) {
            fail(`Invalid runner config update: ${value}`);
        }
        const key = value.slice(0, index);
        updates[key] = value.slice(index + 1);
    }
    return updates;
}
