import fsSync from "node:fs";
import path from "node:path";
import { autoflowBinPath, useElectronAsNodeRuntime } from "./core-registry";
import { shellScriptSingleQuote } from "./shell-path";

function repoRoot(): string {
  return process.env.AUTOFLOW_REPO_ROOT || "";
}

export type Invocation = {
  command: string;
  args: string[];
  env: Record<string, string>;
};

export function cliInvocation(args: unknown[]): Invocation {
  const cliArgs = args.map((arg) => String(arg));
  if (useElectronAsNodeRuntime()) {
    return {
      command: process.execPath,
      args: [autoflowBinPath(repoRoot()), ...cliArgs],
      env: { ELECTRON_RUN_AS_NODE: "1" }
    };
  }
  return {
    command: autoflowBinPath(repoRoot()),
    args: cliArgs,
    env: {}
  };
}

export function requiredTsxCliPath(): string {
  try {
    return require.resolve("tsx/cli", { paths: [repoRoot()] });
  } catch {
    return "";
  }
}

export function runtimeTsInvocation(relativeScriptPath: string, args: unknown[]): Invocation {
  const tsxCli = requiredTsxCliPath();
  if (!tsxCli) {
    return cliInvocation(["tool", "runner-tokens", ...args]);
  }
  const scriptPath = path.join(repoRoot(), "app", "runtime", relativeScriptPath);
  return {
    command: process.execPath,
    args: [tsxCli, scriptPath, ...args.map((arg) => String(arg))],
    env: useElectronAsNodeRuntime() ? { ELECTRON_RUN_AS_NODE: "1" } : {}
  };
}

export function runnerTokensInvocation(args: unknown[]): Invocation {
  return runtimeTsInvocation("system/runner-tokens.ts", args);
}

export function sessionTokenUsageImportDelayMs(): number {
  const configured = Number(process.env.AUTOFLOW_SESSION_TOKEN_USAGE_IMPORT_DEBOUNCE_MS || "");
  if (Number.isFinite(configured) && configured > 0) return configured;
  return 60000;
}

export function ensureAutoflowCliShim({ projectRoot, boardDirName }: { projectRoot: string; boardDirName: string }): {
  binDir: string;
  shimPath: string;
  ok: boolean;
  error: string;
} {
  const boardRoot = path.join(projectRoot, boardDirName);
  const binDir = path.join(boardRoot, "runners", "state", "bin");
  const shimPath = path.join(binDir, "autoflow");
  const nodeRuntime = useElectronAsNodeRuntime() ? process.execPath : "";
  const cliEntry = autoflowBinPath(repoRoot());
  const needsElectron = useElectronAsNodeRuntime() ? "1" : "0";
  const content = [
    "#!/bin/sh",
    "# Generated by Autoflow Desktop. Do not edit.",
    "set -eu",
    `AUTOFLOW_NODE_RUNTIME=${shellScriptSingleQuote(nodeRuntime)}`,
    `AUTOFLOW_CLI_ENTRY=${shellScriptSingleQuote(cliEntry)}`,
    `AUTOFLOW_CLI_NEEDS_ELECTRON=${shellScriptSingleQuote(needsElectron)}`,
    'if [ "$AUTOFLOW_CLI_NEEDS_ELECTRON" = "1" ]; then',
    '  ELECTRON_RUN_AS_NODE=1 exec "$AUTOFLOW_NODE_RUNTIME" "$AUTOFLOW_CLI_ENTRY" "$@"',
    "fi",
    'if [ -x "$AUTOFLOW_CLI_ENTRY" ]; then',
    '  exec "$AUTOFLOW_CLI_ENTRY" "$@"',
    "fi",
    'if [ -n "$AUTOFLOW_NODE_RUNTIME" ]; then',
    '  exec "$AUTOFLOW_NODE_RUNTIME" "$AUTOFLOW_CLI_ENTRY" "$@"',
    "fi",
    'echo "Autoflow CLI entry is not executable: $AUTOFLOW_CLI_ENTRY" >&2',
    "exit 127",
    ""
  ].join("\n");
  try {
    fsSync.mkdirSync(binDir, { recursive: true });
    let existing = "";
    try {
      existing = fsSync.readFileSync(shimPath, "utf8");
    } catch {}
    if (existing !== content) {
      fsSync.writeFileSync(shimPath, content, "utf8");
    }
    fsSync.chmodSync(shimPath, 0o755);
    return { binDir, shimPath, ok: true, error: "" };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      binDir,
      shimPath: "",
      ok: false,
      error: message
    };
  }
}
