import fsSync from "node:fs";
import os from "node:os";
import path from "node:path";

const { app } = require("electron");

// Autoflow 가 과거에 codex Stop hook 을 설치한 흔적을 데스크탑 부팅 시 한 번
// 정리한다. hooks.json 안에 autoflow tool check-stop 명령 또는 "name": "autoflow"
// 식별자가 있으면 그 파일을 삭제한다. 다른 hook 등록은 보존.
function looksLikeAutoflowHookFile(content: string): boolean {
  if (!content) return false;
  if (/Generated by Autoflow/i.test(content)) return true;
  if (/"name"\s*:\s*"autoflow"/i.test(content)) return true;
  if (/autoflow\s+tool\s+check-stop/i.test(content)) return true;
  return false;
}

function removeIfAutoflowHookFile(filePath: string): boolean {
  try {
    const content = fsSync.readFileSync(filePath, "utf8");
    if (!looksLikeAutoflowHookFile(content)) return false;
    fsSync.rmSync(filePath, { force: true });
    return true;
  } catch {
    return false;
  }
}

export function cleanupLegacyStopHooks(): void {
  const removed: string[] = [];

  // 1. user-scope codex home
  const codexHome = process.env.CODEX_HOME && process.env.CODEX_HOME.trim()
    ? path.resolve(process.env.CODEX_HOME)
    : path.join(os.homedir(), ".codex");
  const userHookFile = path.join(codexHome, "hooks.json");
  if (removeIfAutoflowHookFile(userHookFile)) removed.push(userHookFile);

  // 2. isolated codex runner homes (Autoflow Desktop 가 만든 격리 디렉터리)
  try {
    const runnersRoot = path.join(app.getPath("userData"), "codex-runners");
    if (fsSync.existsSync(runnersRoot)) {
      for (const projectDir of fsSync.readdirSync(runnersRoot)) {
        const projectPath = path.join(runnersRoot, projectDir);
        let runnerDirs: string[] = [];
        try { runnerDirs = fsSync.readdirSync(projectPath); } catch { continue; }
        for (const runnerDir of runnerDirs) {
          const hookFile = path.join(projectPath, runnerDir, "hooks.json");
          if (removeIfAutoflowHookFile(hookFile)) removed.push(hookFile);
        }
      }
    }
  } catch {}

  if (removed.length > 0) {
    try {
      // 정리한 파일 목록은 stdout 으로만 출력. main process 가 부팅 직후라
      // renderer 가 없어 IPC 알림은 무의미하다.
      // eslint-disable-next-line no-console
      console.log(`[autoflow] cleaned up ${removed.length} legacy stop-hook file(s):`);
      for (const file of removed) {
        // eslint-disable-next-line no-console
        console.log(`  - ${file}`);
      }
    } catch {}
  }
}
