#!/usr/bin/env bash
# draft-pr.sh — Compose a PR body from a passed Autoflow ticket.
#
# PRD 6 (2026-05-09): worker finalizer calls this after inline merge done so
# the user can run `gh pr create --body-file <output>` for a one-step PR.
# This script NEVER invokes git push, gh login, or any network operation.
#
# Usage:
#   draft-pr.sh <ticket-file> [<completion-commit-hash>]
# Output: PR body markdown on stdout.

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/common.sh"

ticket_file="${1:-}"
commit_hash="${2:-}"

if [ -z "$ticket_file" ] || [ ! -f "$ticket_file" ]; then
  echo "missing ticket file" >&2
  exit 2
fi

ticket_id="$(extract_numeric_id "$ticket_file" 2>/dev/null || true)"
prd_key="$(ticket_scalar_field "$ticket_file" "PRD Key" 2>/dev/null || true)"
title="$(ticket_scalar_field "$ticket_file" "Title" 2>/dev/null || true)"
summary="$(extract_scalar_field_in_section "$ticket_file" "Result" "Summary" 2>/dev/null || true)"
verify_cmd="$(extract_scalar_field_in_section "$ticket_file" "Verification" "Command" 2>/dev/null || true)"
base_commit="$(awk '/^## Worktree/{flag=1; next} /^## /{flag=0} flag && /^- Base Commit:/{
    sub(/^- Base Commit:[[:space:]]*/, "")
    sub(/[[:space:]]+$/, "")
    print
    exit
  }' "$ticket_file" 2>/dev/null || true)"
change_type="$(awk '/^## Ticket/{flag=1; next} /^## /{flag=0} flag && /^- Change Type:/{
    sub(/^- Change Type:[[:space:]]*/, "")
    sub(/[[:space:]]+$/, "")
    print
    exit
  }' "$ticket_file" 2>/dev/null || true)"

prd_upper="$(printf '%s' "$prd_key" | tr '[:lower:]' '[:upper:]')"
[ -n "$prd_upper" ] || prd_upper="UNKNOWN_PRD"
header="[${prd_upper}][ticket_${ticket_id}] ${title}"

diff_stat=""
if [ -n "$base_commit" ] && command -v git >/dev/null 2>&1 && [ -n "${PROJECT_ROOT:-}" ]; then
  diff_stat="$(git -C "$PROJECT_ROOT" diff --stat "${base_commit}..HEAD" 2>/dev/null || true)"
fi

done_when="$(awk '
  /^## Done When/ { in_section=1; next }
  /^## / && in_section { in_section=0 }
  in_section && /^[[:space:]]*- \[[ xX]\]/ { print }
' "$ticket_file" 2>/dev/null || true)"

ticket_rel="$(basename "$ticket_file")"
if [ -n "${BOARD_ROOT:-}" ]; then
  case "$ticket_file" in
    "${BOARD_ROOT}/"*) ticket_rel="${ticket_file#${BOARD_ROOT}/}" ;;
  esac
fi

cat <<EOF
# ${header}

## Summary

- ${summary:-(see ticket)}

## Done When

${done_when:-(no Done When checklist recorded)}

## Diff stat

\`\`\`
${diff_stat:-(no diff stat available — base_commit may be missing)}
\`\`\`

## Metadata

- Source ticket: \`${ticket_rel}\`
- Change Type: \`${change_type:-code}\`
- Verification command: \`${verify_cmd:-(none)}\`
- Base commit: \`${base_commit:-unknown}\`
${commit_hash:+- Completion commit: \`${commit_hash}\`
}
> 🤖 Generated by Autoflow PRD 6 PR-draft autogen. Push the branch yourself, then run \`gh pr create --body-file <this-file>\`.
EOF
